"""add history query product

Revision ID: 0321ebd288df
Revises: 1cc0d6519338
Create Date: 2022-06-22 11:17:39.507997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0321ebd288df'
down_revision = '1cc0d6519338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('history_query', sa.Integer(), nullable=False))
    op.alter_column('product', 'sku',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('product', 'brand',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('product', 'brand',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('product', 'sku',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('product', 'history_query')
    # ### end Alembic commands ###
